version: "3.9"

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
    - PG_DATABASE=
    - PG_USERNAME=
    - PG=PASSWORD=
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
