export const STATUS = {
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  CANCEL: "CANCEL",
};

export const SPEND_TYPE = {
  DEBIT: "DEBIT",
  CREDIT: "CREDIT",
};

export const PAYMENT_TYPE = {
  CASH: "CASH",
  ONLINE: "ONLINE",
  CHEQUE: "CHEQUE",
};

export const EDIT_PO_STATUS = [STATUS.CANCEL, STATUS.PENDING];
