export const STATUS = {
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  CANCEL: "CANCEL",
};

export const SPEND_TYPE = {
  DEBIT: "DEBIT",
  CREDIT: "CREDIT",
};

export const PAYMENT_TYPE = {
  CASH: "CASH",
  ONLINE: "ONLINE",
  CHEQUE: "CHEQUE",
};

export const EDITABLE_STATUS = [STATUS.CANCEL, STATUS.PENDING];

export const DEFAULT_ROWS_LIMIT = 1000;
