name: deploy app to vercel
"on":
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo out a GitHub Actions Secret to the logs"
        run:
          "echo ${{ secrets.VERCEL_TOKEN }} echo ${{ secrets.POSTGRES_HOST }} echo ${{ secrets.POSTGRES_USER }} echo ${{ secrets.POSTGRES_PASSWORD }} echo ${{ secrets.POSTGRES_DB }} echo ${{ secrets.TOKEN_SECRET }} \n\
          echo ${{ secrets.ORG_ID }} \"\n\
          echo ${{ secrets.PROJECT_ID }}'s/./& /g' "

      - uses: actions/checkout@v2
      #add env file to .env.local
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: inventory-system-nextjs # project name in Vercel
          envVariableKeys: POSTGRES_HOST,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,TOKEN_SECRET
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

      # deploy app to vercel
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--stage" #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
